[workspace]
resolver = "3"
members = [
    "app/avvist-til-oppgave",
    "app/test-app",
    "lib/axum_health",
    "lib/health_and_monitoring",
    "lib/paw_rust_base",
    "lib/paw_sqlx",
    "lib/paw_rdkafka_hwm",
    "lib/paw_rdkafka",
]
