[package]
name = "avvist-til-oppgave"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
health = { path = "../../lib/health" }
axum_health = { path = "../../lib/axum_health" }
log = "0.4.29"
log4rs = "1.4.0"
tokio = { version = "1.49.0", features = ["full"] }


