[package]
name = "avvist-til-oppgave"
version = "0.1.0"
edition = "2024"

[dependencies]
paw_rust_base = { path = "../../lib/paw_rust_base" }
axum = "0.8.8"
health_and_monitoring = { path = "../../lib/health_and_monitoring" }
axum_health = { path = "../../lib/axum_health" }
paw_sqlx = { path = "../../lib/paw_sqlx" }
log = "0.4.29"
log4rs = "1.4.0"
tokio = { version = "1.49.0", features = ["full"] }
rdkafka = { version = "0.38.0", features = ["ssl-vendored", "tracing", "tokio"] }
serde = "1.0.228"
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "tls-rustls", "macros", "chrono"] }
futures = "0.3.31"

[dev-dependencies]
testcontainers = "0.16"
testcontainers-modules = { version = "0.4", features = ["postgres"] }
