host = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_UTGANG_PDL_UTGANGBETA1_HOST}"
port = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_UTGANG_PDL_UTGANGBETA1_PORT}"
username = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_UTGANG_PDL_UTGANGBETA1_USERNAME}"
password = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_UTGANG_PDL_UTGANGBETA1_PASSWORD}"
database = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_UTGANG_PDL_UTGANGBETA1_DATABASE}"
