name: Avvist til oppgave - build and deploy
on:
  push:
    branches:
      - main
    paths:
      - 'app/avvist-til-oppgave/**'
      - 'Cargo.lock'
      - 'lib/**'
      - 'Dockerfile'
env:
  APP_NAME: avvist-til-oppgave
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e
        with:
          toolchain: stable
      - run: cargo test -p ${{ env.APP_NAME }}
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e
        with:
          toolchain: stable
      - uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-${{ github.workflow_ref }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: docker-build-push
        uses: nais/docker-build-push@791ebb6f74b82849c742a9bc9c97abe44c6c111f
        id: docker-build-push
        with:
          team: paw
          image_suffix: ${{ env.APP_NAME }}
          build_args: |
            APP=${{ env.APP_NAME }}
            GIT_COMMIT_HASH=${{ github.sha }}

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    if: github.ref == 'refs/heads/main'
    name: Deploy to dev-gcp
    needs: [ test, build ]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@56e14061f2a8437bd9119e7b8f92749a3b288db1
        env:
          CLUSTER: dev-gcp
          RESOURCE: app/${{ env.APP_NAME }}/nais/nais-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
